### ISSUE TITLE
Spaces

### ISSUE THREAD

**Issue by giucu91** [ColorlibHQ/colorlib-coming-soon-maintenence#19]
https://github.com/MachoThemes/colorlib-coming-soon-maintenence/blob/master/templates/template_01/template_01.php#L176

https://github.com/MachoThemes/colorlib-coming-soon-maintenence/blob/master/includes/controls/class_ccsm_control_text_editor.php#L10

Si sa te mai uiti sa vezi daca mai sunt pe vro undeva astfel de spatii dubioase.

**Comment by razvanaldea89** [comment]
Fixed

**Comment by giucu91** [comment]
https://github.com/MachoThemes/colorlib-coming-soon-maintenence/blob/master/templates/template_01/template_01.php#L196

Spatiu inainte de `.`.
