### ISSUE TITLE
Templates -> sticky header

### ISSUE THREAD

**Issue by giucu91** [ColorlibHQ/colorlib-coming-soon-maintenence#32]
Vezi 404 pentru info.

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/48660231-30705780-ea67-11e8-8dc7-61575de5ac69.png)

**Comment by cristianraiber** [comment]
Ar trebui ca sticky header sa aiba width 100% aici.

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/48680311-a5947780-eba2-11e8-9b36-264896589f0c.png)

**Comment by razvanaldea89** [comment]
Cu 100% arata destul de urat. Se duce pana in capat acel header.

**Comment by cristianraiber** [comment]
Ar trebui tratat atunci cu media queries. Eu am rezolutie 2560 x 1440 si arata ca in poza mea :) E clar ca la 1920 x 1080/1200 ar trebui width auto.
