### ISSUE TITLE
Verificat TOATE Template.urile

### ISSUE THREAD

**Issue by giucu91** [ColorlibHQ/colorlib-coming-soon-maintenence#38]
Le verificam pentru urmatoarele chestii : 
- Sa nu avem mai multe elemente in customizer de editat decat sunt pe front ( de ex. daca nu apar iconite de social, nu avem in customizer sectiunea de social, etc. )
- Daca avem setari de background color/text color sa nu aplicam mereu pe toate elementele, ca atunci nu se mai vad anumite text ( de ex. daca avem un element al carui background nu se schimba, nu schimbam nici  text color. )

**Comment by cristianraiber** [comment]
@giucu91 - please look here for my comments: https://github.com/ColorlibHQ/colorlib-coming-soon-maintenence/commit/504713f5b98596b69615b3c7e9dec11d38f5e3d1
