### ISSUE TITLE
issue with the countdown timer

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/colorlib-coming-soon-maintenence#44]
there seems to be an issue with the countdown timer, does not show the correct time https://wordpress.org/support/topic/time-adjuster-isnt-reliable/

**Comment by razvanaldea89** [comment]
Issue with the "jumping back 14 hours" is from the "PM/AM" change

**Comment by cristianraiber** [comment]
@razvanaldea89 - what's the fix for it?

**Comment by razvanaldea89** [comment]
Well, there isn't quite an issue, it is more an understanding of how PM/AM works. As a solution, we could implement 24h time.

**Comment by cristianraiber** [comment]
@razvanaldea89 - I think that's actually a good idea.

**Comment by giucu91** [comment]
Fixed in 1.0.5
