### ISSUE TITLE
Subscribe field text will be overlapped on template 14 

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/colorlib-coming-soon-maintenence#74]
On template 14 the subscribe field text will be overlapped : 
Desktop : https://prnt.sc/vuwdvr
Devices: 
https://prnt.sc/vuwepf

Tested with WP 5.6

**Comment by TeoAlex** [comment]
https://github.com/ColorlibHQ/colorlib-coming-soon-maintenence/assets/19348508/14f493b8-fccc-4e32-a58a-3076ea717bcf


Could not reproduce the issue.
